version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 app:app
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - mynet
  
  nginx:
    depends_on:
      - web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    networks:
      - mynet

  db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/load_db.sh
      - ./db.dump:/db.dump
    networks:
      - mynet

    # command: postgres -D /var/lib/postgresql/data
    # This command allows running postgres in background
    # So that you can import the dump file if needed

networks:
  mynet:

volumes:
  db-data:
