version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./db.dump:/docker-entrypoint-initdb.d/db.dump
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # command: postgres -D /var/lib/postgresql/data
    # This command allows running postgres in background
    # So that you can import the dump file if needed

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
