version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 app:app
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - mynet
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynet
  
  db:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynet
    # command: postgres -D /var/lib/postgresql/data
    # This command allows running postgres in background
    # So that you can import the dump file if needed

networks:
  mynet:

volumes:
  db-data:
