version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./db.dump:/docker-entrypoint-initdb.d/db.dump
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  web:
    build: .
    command: /wait-for-it.sh db:5432 -- gunicorn -b 0.0.0.0:8000 app:app
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
